### ISSUE TITLE
Undefined subroutine &goauth::file

### ISSUE THREAD

**Issue by niceperl** [pscott-au/WebService-GoogleAPI-Client#19]
**Describe the bug**
Undefined subroutine &goauth::file called at /Users/jmprellezo/temp/perl/google-excel/local/bin/goauth line 20.

**To Reproduce**
run: goauth

**Comment by niceperl** [comment]
I added `use Path::Class` and it worked fine

**Comment by rabbiveesh** [comment]
What version are you using?

**Comment by niceperl** [comment]
I have installed version 0.24 with `cpanm`

**Comment by rabbiveesh** [comment]
Wow, my bad. Thanks for reporting. Fixing right now.

**Comment by rabbiveesh** [comment]
thanks for the report, the newest version on CPAN doesn't have this issue anymore.
