### ISSUE TITLE
Fails with perls < 5.14

### ISSUE THREAD

**Issue by andk** [pscott-au/WebService-GoogleAPI-Client#8]
**Describe the bug**

Hi there everybody, did you know that the test suite fails with perls < 5.14?

**To Reproduce**
1. Go to 'http://matrix.cpantesters.org/?dist=WebService-GoogleAPI-Client%200.13'
2. Click on nothing
3. Scroll down to the lines for 5.14 and 5.12
4. See error in that 5.12 is red and 5.14 is green

**Expected behavior**

It would be cool if the code could declare its requirements. That way the FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes . This is not really a requirement, of course. Not for me. I can switch to newer perls. Maybe it would help other people who sit in a project with perl 5.12 or lower and cannot change that easily. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pscott-au** [comment]
Thanks for that. I think I've properly defined the min perl version now in https://github.com/pscott-au/WebService-GoogleAPI-Client/commit/27712515c258c94a9b0af1e72a09be63b180a659 - once I can confirm I will mark this issue as resolved.

**Comment by pscott-au** [comment]
Looks all fixed now - thanks
